name: CI

on: [push]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: [ 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, 3.3 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
      if: matrix.os == 'ubuntu-latest'

    - run: gem install bundler -v 2.1.4

    - uses: actions/checkout@v2

    - run: bundle install --jobs 4 --retry 3

    - run: bundle exec rspec
      env:
        CI: true

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage/coverage.xml
