name: review

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - run: gem install bundler -v 2.1.4

    - uses: actions/checkout@v2

    - run: bundle install --jobs 4 --retry 3

    - name: Run Rubocop with Reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec rubocop --fail-level E \
          | reviewdog -f=rubocop -reporter=github-pr-review
